backend:
  name: github
  repo: freeserverproject/freeserver-wiki
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "固定ページ"
    name: "fixedPages"
    folder: "docs"
    create: true
    fields:
      - { label: "Home", name: "home", widget: "hidden", default: false }
      - { label: "タイトル(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "アイテム"
    name: "item"
    folder: "docs/item"
    create: true
    fields:
      - { label: "アイテム名(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "運営一覧"
    name: "admins"
    folder: "docs/admins"
    create: true
    fields:
      - { label: "ユーザー名(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "イベント"
    name: "events"
    folder: "docs/event"
    create: true
    fields:
      - { label: "イベント名(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "プラグイン"
    name: "plugins"
    folder: "docs/plugin"
    create: true
    fields:
      - { label: "プラグイン名(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "規約類"
    name: "terms"
    folder: "docs/terms"
    create: true
    fields:
      - { label: "タイトル(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "ワールド一覧"
    name: "worlds"
    folder: "docs/world"
    create: true
    fields:
      - { label: "タイトル(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "鉄道"
    name: "trains"
    folder: "docs/trains"
    create: true
    fields:
      - { label: "タイトル(新規記事は英語が良き)", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "サイドバー", name: "sidebar", widget: "boolean", default: true }
      - { label: "本文", name: "body", widget: "markdown" }
